
services:
  bot:
    build:
      context: ./base-js-baileys-json
    container_name: bot_service
    restart: always
    env_file:
      - ./base-js-baileys-json/.env
    ports:
      - "3009:3009"  # API Server (incluye endpoint /qr)
      - "3001:3001"  # Bot HTTP Server
    volumes:
      - ./base-js-baileys-json:/app
      - /app/node_modules

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard_service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - bot
