services:
  # ============================================
  # BOT 1 - Asesor 1
  # ============================================
  bot1:
    build:
      context: ./bot1
      dockerfile: Dockerfile
    container_name: bot1_asesor1
    restart: unless-stopped
    env_file:
      - ./bot1/.env
    environment:
      - PORT=3001
      - API_PORT=3009
      - BOT_NAME=Asesor 1
      - BOT_IDENTIFIER=bot1
    ports:
      - "3001:3001"  # Bot HTTP Server
      - "3009:3009"  # API Server
    volumes:
      - ./bot1:/app
      - /app/node_modules
      - bot1_sessions:/app/bot_sessions
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 2 - Asesor 2
  # ============================================
  bot2:
    build:
      context: ./bot2
      dockerfile: Dockerfile
    container_name: bot2_asesor2
    restart: unless-stopped
    env_file:
      - ./bot2/.env
    environment:
      - PORT=3002
      - API_PORT=3010
      - BOT_NAME=Asesor 2
      - BOT_IDENTIFIER=bot2
    ports:
      - "3002:3002"
      - "3010:3010"
    volumes:
      - ./bot2:/app
      - /app/node_modules
      - bot2_sessions:/app/bot_sessions
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 3 - Asesor 3
  # ============================================
  bot3:
    build:
      context: ./bot3
      dockerfile: Dockerfile
    container_name: bot3_asesor3
    restart: unless-stopped
    env_file:
      - ./bot3/.env
    environment:
      - PORT=3003
      - API_PORT=3011
      - BOT_NAME=Asesor 3
      - BOT_IDENTIFIER=bot3
    ports:
      - "3003:3003"
      - "3011:3011"
    volumes:
      - ./bot3:/app
      - /app/node_modules
      - bot3_sessions:/app/bot_sessions
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3011/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 4 - Asesor 4
  # ============================================
  bot4:
    build:
      context: ./bot4
      dockerfile: Dockerfile
    container_name: bot4_asesor4
    restart: unless-stopped
    env_file:
      - ./bot4/.env
    environment:
      - PORT=3004
      - API_PORT=3012
      - BOT_NAME=Asesor 4
      - BOT_IDENTIFIER=bot4
    ports:
      - "3004:3004"
      - "3012:3012"
    volumes:
      - ./bot4:/app
      - /app/node_modules
      - bot4_sessions:/app/bot_sessions
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3012/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 5 - Asesor 5
  # ============================================
  bot5:
    build:
      context: ./bot5
      dockerfile: Dockerfile
    container_name: bot5_asesor5
    restart: unless-stopped
    env_file:
      - ./bot5/.env
    environment:
      - PORT=3005
      - API_PORT=3013
      - BOT_NAME=Asesor 5
      - BOT_IDENTIFIER=bot5
    ports:
      - "3005:3005"
      - "3013:3013"
    volumes:
      - ./bot5:/app
      - /app/node_modules
      - bot5_sessions:/app/bot_sessions
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3013/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # DASHBOARD
  # ============================================
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard_whatsapp
    restart: unless-stopped
    env_file:
      - ./dashboard/.env.local
    environment:
      - PORT=3000
    ports:
      - "3100:3000"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
      - /app/.next
    networks:
      - whatsapp_network
    depends_on:
      - bot1
      - bot2
      - bot3
      - bot4
      - bot5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

# ============================================
# NETWORKS
# ============================================
networks:
  whatsapp_network:
    driver: bridge

# ============================================
# VOLUMES (para persistir sesiones de WhatsApp)
# ============================================
volumes:
  bot1_sessions:
  bot2_sessions:
  bot3_sessions:
  bot4_sessions:
  bot5_sessions:
