services:
  # ============================================
  # BOT 1 - Asesor 1
  # ============================================
  bot1:
    build:
      context: ./bot1
      dockerfile: Dockerfile
    container_name: bot1_asesor1
    restart: unless-stopped
    env_file:
      - ./bot1/.env
    environment:
      - PORT=3001
      - API_PORT=3009
      - BOT_NAME=Asesor 1
      - BOT_IDENTIFIER=bot1
    ports:
      - "3001:3001"
      - "3009:3009"
    volumes:
      - bot1_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 2 - Asesor 2
  # ============================================
  bot2:
    build:
      context: ./bot2
      dockerfile: Dockerfile
    container_name: bot2_asesor2
    restart: unless-stopped
    env_file:
      - ./bot2/.env
    environment:
      - PORT=3002
      - API_PORT=3010
      - BOT_NAME=Asesor 2
      - BOT_IDENTIFIER=bot2
    ports:
      - "3002:3002"
      - "3010:3010"
    volumes:
      - bot2_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 3 - Asesor 3
  # ============================================
  bot3:
    build:
      context: ./bot3
      dockerfile: Dockerfile
    container_name: bot3_asesor3
    restart: unless-stopped
    env_file:
      - ./bot3/.env
    environment:
      - PORT=3003
      - API_PORT=3011
      - BOT_NAME=Asesor 3
      - BOT_IDENTIFIER=bot3
    ports:
      - "3003:3003"
      - "3011:3011"
    volumes:
      - bot3_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3011/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 4 - Asesor 4
  # ============================================
  bot4:
    build:
      context: ./bot4
      dockerfile: Dockerfile
    container_name: bot4_asesor4
    restart: unless-stopped
    env_file:
      - ./bot4/.env
    environment:
      - PORT=3004
      - API_PORT=3012
      - BOT_NAME=Asesor 4
      - BOT_IDENTIFIER=bot4
    ports:
      - "3004:3004"
      - "3012:3012"
    volumes:
      - bot4_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3012/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 5 - Asesor 5
  # ============================================
  bot5:
    build:
      context: ./bot5
      dockerfile: Dockerfile
    container_name: bot5_asesor5
    restart: unless-stopped
    env_file:
      - ./bot5/.env
    environment:
      - PORT=3005
      - API_PORT=3013
      - BOT_NAME=Asesor 5
      - BOT_IDENTIFIER=bot5
    ports:
      - "3005:3005"
      - "3013:3013"
    volumes:
      - bot5_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3013/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 6 - Asesor 6
  # ============================================
  bot6:
    build:
      context: ./bot6
      dockerfile: Dockerfile
    container_name: bot6_asesor6
    restart: unless-stopped
    env_file:
      - ./bot6/.env
    environment:
      - PORT=3006
      - API_PORT=3014
      - BOT_NAME=Asesor 6
      - BOT_IDENTIFIER=bot6
    ports:
      - "3006:3006"
      - "3014:3014"
    volumes:
      - bot6_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3014/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 7 - Asesor 7
  # ============================================
  bot7:
    build:
      context: ./bot7
      dockerfile: Dockerfile
    container_name: bot7_asesor7
    restart: unless-stopped
    env_file:
      - ./bot7/.env
    environment:
      - PORT=3007
      - API_PORT=3015
      - BOT_NAME=Asesor 7
      - BOT_IDENTIFIER=bot7
    ports:
      - "3007:3007"
      - "3015:3015"
    volumes:
      - bot7_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3015/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 8 - Asesor 8
  # ============================================
  bot8:
    build:
      context: ./bot8
      dockerfile: Dockerfile
    container_name: bot8_asesor8
    restart: unless-stopped
    env_file:
      - ./bot8/.env
    environment:
      - PORT=3008
      - API_PORT=3016
      - BOT_NAME=Asesor 8
      - BOT_IDENTIFIER=bot8
    ports:
      - "3008:3008"
      - "3016:3016"
    volumes:
      - bot8_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3016/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 9 - Asesor 9
  # ============================================
  bot9:
    build:
      context: ./bot9
      dockerfile: Dockerfile
    container_name: bot9_asesor9
    restart: unless-stopped
    env_file:
      - ./bot9/.env
    environment:
      - PORT=3009
      - API_PORT=3017
      - BOT_NAME=Asesor 9
      - BOT_IDENTIFIER=bot9
    ports:
      - "3009:3009"
      - "3017:3017"
    volumes:
      - bot9_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3017/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # BOT 10 - Asesor 10
  # ============================================
  bot10:
    build:
      context: ./bot10
      dockerfile: Dockerfile
    container_name: bot10_asesor10
    restart: unless-stopped
    env_file:
      - ./bot10/.env
    environment:
      - PORT=3010
      - API_PORT=3018
      - BOT_NAME=Asesor 10
      - BOT_IDENTIFIER=bot10
    ports:
      - "3010:3010"
      - "3018:3018"
    volumes:
      - bot10_sessions:/app/baileys_store_multi
    networks:
      - whatsapp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3018/status"]
      interval: 30s
      timeout: 10s
      retries: 3

# ============================================
# NETWORKS
# ============================================
networks:
  whatsapp_network:
    driver: bridge

# ============================================
# VOLUMES (para persistir sesiones de WhatsApp)
# ============================================
volumes:
  bot1_sessions:
  bot2_sessions:
  bot3_sessions:
  bot4_sessions:
  bot5_sessions:
  bot6_sessions:
  bot7_sessions:
  bot8_sessions:
  bot9_sessions:
  bot10_sessions:
